# Generated by Django 5.0.3 on 2024-03-08 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_documents_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documents',
            name='author',
        ),
        migrations.RemoveField(
            model_name='documents',
            name='content',
        ),
        migrations.RemoveField(
            model_name='documents',
            name='title',
        ),
    ]
