# Generated by Django 5.0.3 on 2024-03-11 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_alter_documents_author_alter_medication_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patientuser'),
        ),
        migrations.AlterField(
            model_name='medication',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patientuser'),
        ),
    ]
