# Generated by Django 4.2.2 on 2024-03-13 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0007_alter_documents_author_alter_medication_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientuser',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='patientuser',
            name='blood_group',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], default=('A+', 'A+'), max_length=3),
        ),
        migrations.AddField(
            model_name='patientuser',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default=('male', 'Male'), max_length=10),
        ),
    ]
