# Generated by Django 5.0.3 on 2024-03-13 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0008_patientuser_age_patientuser_blood_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='type',
            field=models.CharField(choices=[('prescription', 'Prescription'), ('lab_report', 'Lab Report'), ('scans', 'Scans'), ('medical_certificate', 'Medical Certificate')], default='prescription', max_length=20),
        ),
    ]
