# Generated by Django 5.0.1 on 2024-04-10 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0009_documents_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='document_name',
            field=models.CharField(default=10, max_length=100),
            preserve_default=False,
        ),
    ]
