# Generated by Django 5.0.1 on 2024-04-11 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0010_documents_document_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
