# Generated by Django 5.0.1 on 2024-04-11 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0011_documents_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='document_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
