# Generated by Django 5.0.1 on 2024-04-11 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0013_alter_documents_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='type',
            field=models.CharField(choices=[('prescription', 'Prescription'), ('lab_report', 'Lab Report'), ('scans', 'Scans'), ('medical_certificate', 'Medical Certificate')], default='prescription', max_length=20),
        ),
    ]
