# Generated by Django 5.0.3 on 2024-04-11 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0014_alter_documents_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='comments',
            field=models.CharField(default='None', max_length=500),
        ),
    ]
