# Generated by Django 5.0.1 on 2024-04-14 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0015_documents_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='comments',
            field=models.CharField(default='None', max_length=500),
        ),
    ]
