# Generated by Django 5.0.3 on 2024-03-09 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_doctoruser'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctoruser',
            name='password',
            field=models.CharField(default='none', max_length=200),
        ),
    ]
