# Generated by Django 5.0.3 on 2024-03-09 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0004_doctoruser_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctoruser',
            name='password',
        ),
        migrations.RemoveField(
            model_name='doctoruser',
            name='username',
        ),
    ]
