# Generated by Django 5.0.3 on 2024-03-15 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0007_day_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='shareddocument',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
