# Generated by Django 5.0.3 on 2024-03-15 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0008_appointment'),
        ('patients', '0009_documents_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='patientID',
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='patients.patientuser'),
        ),
    ]
