# Generated by Django 5.0.3 on 2024-03-15 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0009_remove_appointment_patientid_appointment_patient'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['-date']},
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='time',
            new_name='date',
        ),
    ]
