# Generated by Django 5.0.3 on 2024-03-15 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0008_shareddocument_verified'),
        ('doctors', '0010_alter_appointment_options_and_more'),
    ]

    operations = [
    ]
