# Generated by Django 5.0.1 on 2024-04-11 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0011_merge_20240315_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='shareddocument',
            name='document_name',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
