# Generated by Django 5.0.1 on 2024-04-12 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0012_shareddocument_document_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='shareddocument',
            name='comments',
            field=models.CharField(default='None', max_length=500),
        ),
    ]
